apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-repl-restore
spec:
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  bootstrapFrom:
    backupRef:
      name: mariadb-repl-mariabackup
    type: mariabackup
    fileName: mariabackup-2023-12-25T18:32:39Z

  image: mariadb:11.0.3

  port: 3306

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

  env:
    - name: TZ
      value: SYSTEM
    - name: MARIADB_ROOT_PASSWORD
      value: mariadb
